language: bash
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

before_script:
- cp variables.conf.example variables.conf

script:
- bash -c 'shellcheck -x cron-release.sh'
